spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8201
spring: 
  profiles: dev
  application: 
    name: microservice-cloud-config-client
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7002/eureka/
---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: eureka-server-7001
eureka:
  instance:
    hostname: localhost  # Eureka服务端实例名
    instance-id:  eureka-server-7001 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以显示ip信息
  client:
    #registerWithEureka: false  # 实例是否在eureka服务器上注册自己的信息以供其他服务发现（默认为true）
    #fetchRegistry: false  # 此客户端是否获取eureka服务器注册表上的注册信息（默认为true,）
    serviceUrl:
      # 与Eureka注册服务中心的通信zone和url地址,用于查询服务和注册服务
      defaultZone:  http://127.0.0.1:7002/eureka/
  # 在开发环境时关闭服务心跳检测提示，在生产环境需要改为True
  server:
    enable-self-preservation: false
